# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: bionic

python:
  - 3.7
virtualenv:
    system_site_package: true
before_install:
 - sudo add-apt-repository -y ppa:edd/misc
 - sudo apt-get update
 - pip install -r requirements.txt
install:
    make build
script:
 - python -m unittest discover